apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-loader
spec:
  schedule: "00 04 * * *"
  timeZone: "US/Central"
  jobTemplate:
    spec:
      template:
        spec: 
          restartPolicy: Never
          hostNetwork: true
          containers:
            - name: mongo-loader
              image: techsvcdtiregistry.azurecr.io/mongo-loader:latest
              imagePullPolicy: Always
