kind: Pod
apiVersion: v1
metadata:
  name: nginx-blob
spec:
  nodeSelector:
    "kubernetes.io/os": linux
  containers:
    - name: nginx-blob
      image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      volumeMounts:
        - mountPath: "/mnt/blob"
          name: blob01
  volumes:
    - name: blob01
      persistentVolumeClaim:
        claimName: pvc-blob
