apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
spec:
  capacity:
    storage: 1Pi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-nfs-premium
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: ilassistantpoc_aks-scrapy-redis
    volumeAttributes:
      resourceGroup: dti-container-registry
      storageAccount: assistantkubestorage
      containerName: aks-scrapy-redis
      protocol: nfs
